import { Noto_Sans_JP, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const noto = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans", 
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto", 
  display: "swap",
});

export const metadata = {
  title: {
    
   template: "%s | SAMPLE CORP.",
   default:"SAMPLE CORP.",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja" className={`${noto.variable} ${roboto.variable}`}>
      <body>
        <Header />
        <main className="container mx-auto p-4">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
