import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: {
    
   template: "%s | Create Next App",
   default:"Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main className="container mx-auto p-4">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
